service:
  type: ClusterIP

auth:
  adminUser: admin

ingress:
  enabled: true
  extraTls:
  - hosts:
    - ""
    secretName: tls-keycloak-ingress

proxyAddressForwarding: true

replicaCount: 2

# Enable if replicaCount > 1
serviceDiscovery:
  enabled: true

resources:
  limits: {}
  requests:
    cpu: 200m
    memory: 1000Mi

rbac:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list